name: secrets-to-env

on: push

jobs:
  test_env:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: execute py script
      run: python main.py
      env:
        AMAZON_S3_AWS_ACCESS_KEY_ID: ${{ secrets.AMAZON_S3_AWS_ACCESS_KEY_ID }} 
