name: secrets-to-env

on:
  workflow_dispatch:
    

env:
  AMAZON_S3_AWS_ACCESS_KEY_ID: ${{ secrets.AMAZON_S3_AWS_ACCESS_KEY_ID }}
  AMAZON_S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_S3_AWS_SECRET_ACCESS_KEY }}
  PIPELIFE_PIPELIFE_CLIENT_ID: ${{ secrets.PIPELIFE_PIPELIFE_CLIENT_ID }}
  PIPELIFE_PIPELIFE_SECRET: ${{ secrets.PIPELIFE_PIPELIFE_SECRET }}
  PIPELIFE_PIPELIFE_USER: ${{ secrets.PIPELIFE_PIPELIFE_USER }}
  PIPELIFE_PIPELIFE_PASSWORD: ${{ secrets.PIPELIFE_PIPELIFE_PASSWORD }}
  PIPELIFE_BANENOR_CLIENT_ID: ${{ secrets.PIPELIFE_BANENOR_CLIENT_ID }}
  PIPELIFE_BANENOR_SECRET: ${{ secrets.PIPELIFE_BANENOR_SECRET }}
  PIPELIFE_BANENOR_USER: ${{ secrets.PIPELIFE_BANENOR_USER }}
  PIPELIFE_BANENOR_PASSWORD: ${{ secrets.PIPELIFE_BANENOR_PASSWORD }}
  MET_FROST_CLIENT_ID: ${{ secrets.MET_FROST_CLIENT_ID }}
  MET_FROST_SECRET_PASSWORD: ${{ secrets.MET_FROST_SECRET_PASSWORD }}

  
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
