name: secrets-to-env

on:
  workflow_dispatch:
    

env:
  key: ${{ secrets.AMAZON_S3_AWS_ACCESS_KEY_ID }} 
  
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Run Python Script
